name: scikit-learn-course
channels:
  - emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - scikit-learn >= 1.6
  # 2025-11-30: scipy 1.14 is the latest version available and needs numpy<2.3
  # (this avoids scipy UserWarning)
  - numpy<2.3
  - pandas >= 1
  - matplotlib-base
  - seaborn >= 0.13
  - plotly >= 5.10
  - IPython
  - packaging
